FROM nginx:alpine

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    touch /var/run/nginx.pid && chown nginx:nginx /var/run/nginx.pid

COPY repo-documentation.html /usr/share/nginx/html/index.html

USER nginx

EXPOSE 80
