sonar.projectKey=Cognition-Partner-Workshops_app_timesheet
sonar.projectName=Client Timesheet App
sonar.organization=cognition-partner-workshops

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,docker/**,load-tests/**
sonar.test.exclusions=**/__tests__/**,**/*.test.js,**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
