# frozen_string_literal: true

require 'rspec/core/rake_task'
require 'cucumber/rake/task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/e2e/**/*_spec.rb'
end

Cucumber::Rake::Task.new(:cucumber) do |t|
  t.cucumber_opts = '--require features/support --require features/step_definitions src/__tests__/e2e/features --format pretty'
end

desc 'Run all Ruby E2E tests (RSpec + Cucumber)'
task e2e: %i[spec cucumber]

task default: :e2e
