apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timesheet-app-data
  namespace: timesheet-app
  labels:
    app.kubernetes.io/name: timesheet-app
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
