var countryCities = {
    "Albania": [
        { name: "Tirana", population: 0.42, area: "41 km\u00B2", founded: "1614", landmarks: ["Skanderbeg Square", "Et'hem Bej Mosque", "Bunk'Art Museum"], gdp: "\u20AC5.2B", avgSalary: "\u20AC450/mo", description: "Albania's vibrant capital and largest city, Tirana is a colorful blend of Ottoman, Italian, and modern architecture with a booming cafe culture." },
        { name: "Durr\u00EBs", population: 0.20, area: "36 km\u00B2", founded: "627 BC", landmarks: ["Roman Amphitheatre", "Byzantine Forum", "Durr\u00EBs Beach"], gdp: "\u20AC2.1B", avgSalary: "\u20AC380/mo", description: "Albania's main port city and second largest, Durr\u00EBs boasts ancient Roman ruins alongside popular Adriatic beaches." },
        { name: "Vlor\u00EB", population: 0.13, area: "29 km\u00B2", founded: "6th century BC", landmarks: ["Independence Monument", "Muradie Mosque", "Zvernec Island"], gdp: "\u20AC1.3B", avgSalary: "\u20AC350/mo", description: "A coastal city where Albanian independence was declared in 1912, known for its beautiful riviera and historical significance." },
        { name: "Elbasan", population: 0.10, area: "17 km\u00B2", founded: "1466", landmarks: ["Elbasan Castle", "King Mosque", "Ethnographic Museum"], gdp: "\u20AC0.9B", avgSalary: "\u20AC330/mo", description: "Central Albanian city with Ottoman-era fortifications and a growing industrial base." },
        { name: "Shkod\u00EBr", population: 0.09, area: "13 km\u00B2", founded: "4th century BC", landmarks: ["Rozafa Castle", "Shkod\u00EBr Lake", "Lead Mosque"], gdp: "\u20AC0.8B", avgSalary: "\u20AC320/mo", description: "One of the oldest cities in Europe, Shkod\u00EBr sits on a stunning lake and is considered Albania's cultural capital." }
    ],
    "Austria": [
        { name: "Vienna", population: 2.00, area: "415 km\u00B2", founded: "500 BC", landmarks: ["Sch\u00F6nbrunn Palace", "St. Stephen's Cathedral", "Belvedere Palace", "Vienna State Opera", "Prater"], gdp: "\u20AC110B", avgSalary: "\u20AC2,800/mo", description: "Austria's imperial capital, Vienna consistently ranks as one of the world's most liveable cities, renowned for its classical music heritage, coffeehouse culture, and stunning Baroque architecture." },
        { name: "Graz", population: 0.29, area: "128 km\u00B2", founded: "1128", landmarks: ["Schlossberg", "Kunsthaus", "Murinsel", "Eggenberg Palace"], gdp: "\u20AC18B", avgSalary: "\u20AC2,400/mo", description: "Austria's second city and a UNESCO City of Design, Graz blends medieval old town charm with cutting-edge contemporary architecture." },
        { name: "Linz", population: 0.21, area: "96 km\u00B2", founded: "799", landmarks: ["Ars Electronica Center", "Lentos Art Museum", "P\u00F6stlingberg"], gdp: "\u20AC15B", avgSalary: "\u20AC2,500/mo", description: "A Danube city transformed from industrial hub to European Capital of Culture, known for technology arts and the Linzer Torte." },
        { name: "Salzburg", population: 0.16, area: "66 km\u00B2", founded: "696", landmarks: ["Hohensalzburg Fortress", "Mozart's Birthplace", "Mirabell Gardens", "Getreidegasse"], gdp: "\u20AC12B", avgSalary: "\u20AC2,600/mo", description: "Mozart's birthplace and setting of The Sound of Music, Salzburg's baroque old town is a UNESCO World Heritage Site." },
        { name: "Innsbruck", population: 0.13, area: "105 km\u00B2", founded: "1180", landmarks: ["Golden Roof", "Nordkette", "Hofburg Palace", "Bergisel Ski Jump"], gdp: "\u20AC9B", avgSalary: "\u20AC2,500/mo", description: "Capital of the Alps, Innsbruck has hosted the Winter Olympics twice and offers world-class skiing minutes from its historic center." }
    ],
    "Belgium": [
        { name: "Brussels", population: 1.21, area: "161 km\u00B2", founded: "979", landmarks: ["Grand Place", "Atomium", "Manneken Pis", "European Parliament"], gdp: "\u20AC85B", avgSalary: "\u20AC2,700/mo", description: "The de facto capital of the EU, Brussels is a cosmopolitan city famous for its Art Nouveau architecture, chocolate, waffles, and comic strip art." },
        { name: "Antwerp", population: 0.53, area: "204 km\u00B2", founded: "900", landmarks: ["Cathedral of Our Lady", "MAS Museum", "Central Station", "Diamond District"], gdp: "\u20AC42B", avgSalary: "\u20AC2,600/mo", description: "Europe's second-largest port and the world's diamond capital, Antwerp is also a fashion and art powerhouse with Rubens' legacy." },
        { name: "Ghent", population: 0.26, area: "156 km\u00B2", founded: "630", landmarks: ["Gravensteen Castle", "St. Bavo's Cathedral", "Graslei", "Ghent Altarpiece"], gdp: "\u20AC20B", avgSalary: "\u20AC2,400/mo", description: "A medieval gem with more listed buildings than any Belgian city, Ghent is a vibrant university town with stunning canal architecture." },
        { name: "Charleroi", population: 0.20, area: "102 km\u00B2", founded: "1666", landmarks: ["Photography Museum", "Bois du Cazier", "Town Hall"], gdp: "\u20AC12B", avgSalary: "\u20AC2,100/mo", description: "Once an industrial powerhouse, Charleroi is reinventing itself as a creative city with a growing cultural and street art scene." },
        { name: "Li\u00E8ge", population: 0.20, area: "69 km\u00B2", founded: "558", landmarks: ["Li\u00E8ge-Guillemins Station", "Montagne de Bueren", "Grand Curtius Museum"], gdp: "\u20AC14B", avgSalary: "\u20AC2,200/mo", description: "The 'Ardent City' on the Meuse river is known for its festive spirit, Calatrava-designed station, and Walloon cultural heritage." }
    ],
    "Bulgaria": [
        { name: "Sofia", population: 1.31, area: "492 km\u00B2", founded: "7th century BC", landmarks: ["Alexander Nevsky Cathedral", "Vitosha Mountain", "National Palace of Culture"], gdp: "\u20AC32B", avgSalary: "\u20AC900/mo", description: "One of Europe's oldest capitals, Sofia sits at the foot of Vitosha Mountain and blends Roman ruins, Ottoman mosques, and Soviet-era monuments." },
        { name: "Plovdiv", population: 0.35, area: "102 km\u00B2", founded: "6000 BC", landmarks: ["Ancient Theatre", "Old Town", "Kapana District"], gdp: "\u20AC7B", avgSalary: "\u20AC750/mo", description: "One of the world's oldest continuously inhabited cities, Plovdiv was European Capital of Culture 2019, with a spectacular Roman amphitheatre." },
        { name: "Varna", population: 0.34, area: "154 km\u00B2", founded: "585 BC", landmarks: ["Sea Garden", "Roman Baths", "Gold of Varna Museum"], gdp: "\u20AC5B", avgSalary: "\u20AC700/mo", description: "Bulgaria's maritime capital on the Black Sea, known for the world's oldest gold treasure and vibrant summer resort life." },
        { name: "Burgas", population: 0.20, area: "254 km\u00B2", founded: "1st century", landmarks: ["Sea Garden", "Island of St. Anastasia", "Archaeological Museum"], gdp: "\u20AC3.5B", avgSalary: "\u20AC650/mo", description: "A major Black Sea port and gateway to Bulgaria's southern beach resorts, with a charming seaside garden and lakes." },
        { name: "Ruse", population: 0.14, area: "127 km\u00B2", founded: "1st century", landmarks: ["Danube Bridge", "Profit Yielding Building", "Pantheon of National Revival Heroes"], gdp: "\u20AC2B", avgSalary: "\u20AC600/mo", description: "The 'Little Vienna' on the Danube, Ruse has Bulgaria's richest collection of Neo-Baroque and Neo-Rococo architecture." }
    ],
    "Croatia": [
        { name: "Zagreb", population: 0.81, area: "641 km\u00B2", founded: "1094", landmarks: ["Ban Jela\u010Di\u0107 Square", "St. Mark's Church", "Museum of Broken Relationships", "Dolac Market"], gdp: "\u20AC22B", avgSalary: "\u20AC1,100/mo", description: "Croatia's capital combines Austro-Hungarian elegance with a thriving cafe culture, excellent museums, and a charming upper and lower town." },
        { name: "Split", population: 0.18, area: "79 km\u00B2", founded: "305 AD", landmarks: ["Diocletian's Palace", "Riva Promenade", "Marjan Hill", "Cathedral of St. Domnius"], gdp: "\u20AC5B", avgSalary: "\u20AC1,000/mo", description: "Built around and within a Roman emperor's palace, Split is a living ancient monument and gateway to Croatia's stunning islands." },
        { name: "Rijeka", population: 0.13, area: "44 km\u00B2", founded: "Roman era", landmarks: ["Trsat Castle", "Korzo", "Astronomical Centre"], gdp: "\u20AC3.5B", avgSalary: "\u20AC950/mo", description: "Croatia's principal port and European Capital of Culture 2020, Rijeka has a gritty charm and vibrant arts scene." },
        { name: "Osijek", population: 0.10, area: "171 km\u00B2", founded: "Roman era", landmarks: ["Tvr\u0111a Fortress", "Church of St. Peter and Paul", "Copacabana Beach"], gdp: "\u20AC2B", avgSalary: "\u20AC850/mo", description: "The largest city in Slavonia, Osijek charms visitors with its baroque fortress, riverside promenades, and continental Croatian cuisine." },
        { name: "Zadar", population: 0.07, area: "25 km\u00B2", founded: "9th century BC", landmarks: ["Sea Organ", "Sun Salutation", "Roman Forum", "St. Donatus Church"], gdp: "\u20AC1.8B", avgSalary: "\u20AC900/mo", description: "Hitchcock called Zadar's sunset the most beautiful in the world. Its Sea Organ and Sun Salutation are unique architectural installations." }
    ],
    "Czech Republic": [
        { name: "Prague", population: 1.35, area: "496 km\u00B2", founded: "885", landmarks: ["Charles Bridge", "Prague Castle", "Old Town Square", "Astronomical Clock", "Dancing House"], gdp: "\u20AC72B", avgSalary: "\u20AC1,600/mo", description: "The 'City of a Hundred Spires' enchants with its Gothic, Renaissance, and Baroque architecture, world-famous beer culture, and vibrant nightlife." },
        { name: "Brno", population: 0.38, area: "230 km\u00B2", founded: "1243", landmarks: ["Spilberk Castle", "Villa Tugendhat", "Cathedral of St. Peter and Paul"], gdp: "\u20AC15B", avgSalary: "\u20AC1,400/mo", description: "Czech Republic's second city and a tech hub, Brno has a UNESCO-listed modernist villa, excellent wine region, and lively student scene." },
        { name: "Ostrava", population: 0.29, area: "214 km\u00B2", founded: "1267", landmarks: ["Lower V\u00EDtkovice", "Silesian-Ostrava Castle", "Stodolni Street"], gdp: "\u20AC9B", avgSalary: "\u20AC1,200/mo", description: "A former steel city reinvented as a cultural destination, with industrial heritage sites turned into music venues and galleries." },
        { name: "Plze\u0148", population: 0.17, area: "138 km\u00B2", founded: "1295", landmarks: ["Pilsner Urquell Brewery", "Cathedral of St. Bartholomew", "Great Synagogue"], gdp: "\u20AC7B", avgSalary: "\u20AC1,300/mo", description: "Birthplace of Pilsner beer and European Capital of Culture 2015, Plze\u0148 has the world's third-largest synagogue." },
        { name: "Liberec", population: 0.10, area: "106 km\u00B2", founded: "1352", landmarks: ["Je\u0161t\u011Bd Tower", "Liberec Zoo", "North Bohemian Museum"], gdp: "\u20AC4B", avgSalary: "\u20AC1,100/mo", description: "A mountain city known for its iconic TV tower designed by Karel Hubacek and gateway to the Jizera Mountains ski region." }
    ],
    "Denmark": [
        { name: "Copenhagen", population: 0.80, area: "88 km\u00B2", founded: "1167", landmarks: ["Tivoli Gardens", "The Little Mermaid", "Nyhavn", "Christiania", "Rosenborg Castle"], gdp: "\u20AC95B", avgSalary: "\u20AC3,800/mo", description: "A design capital and cycling paradise, Copenhagen consistently ranks as the world's happiest city with its hygge culture, Michelin restaurants, and carbon-neutral ambitions." },
        { name: "Aarhus", population: 0.28, area: "91 km\u00B2", founded: "770", landmarks: ["ARoS Museum", "The Old Town", "Aarhus Cathedral", "Moesg\u00E5rd Museum"], gdp: "\u20AC22B", avgSalary: "\u20AC3,400/mo", description: "Denmark's second city and European Capital of Culture 2017, Aarhus is a youthful university town with world-class museums." },
        { name: "Odense", population: 0.18, area: "304 km\u00B2", founded: "988", landmarks: ["Hans Christian Andersen Museum", "Brandts", "Egeskov Castle"], gdp: "\u20AC10B", avgSalary: "\u20AC3,200/mo", description: "Birthplace of Hans Christian Andersen, Odense is a charming city with a brand-new fairytale museum and cycling-friendly streets." },
        { name: "Aalborg", population: 0.12, area: "1,144 km\u00B2", founded: "1040", landmarks: ["Utzon Center", "Aalborg Tower", "Lindholm H\u00F8je Viking Burial Ground"], gdp: "\u20AC8B", avgSalary: "\u20AC3,100/mo", description: "Northern Denmark's largest city, transformed from industrial town to cultural destination with its Utzon-designed waterfront." },
        { name: "Esbjerg", population: 0.07, area: "742 km\u00B2", founded: "1868", landmarks: ["Men at Sea Sculpture", "Fisheries Museum", "Water Tower"], gdp: "\u20AC5B", avgSalary: "\u20AC3,000/mo", description: "Denmark's fifth city and key North Sea energy port, gateway to the Wadden Sea National Park (UNESCO)." }
    ],
    "Finland": [
        { name: "Helsinki", population: 0.66, area: "214 km\u00B2", founded: "1550", landmarks: ["Helsinki Cathedral", "Suomenlinna", "Temppeliaukio Church", "Oodi Library"], gdp: "\u20AC55B", avgSalary: "\u20AC3,200/mo", description: "A design and technology capital surrounded by sea, Helsinki blends Art Nouveau architecture with cutting-edge innovation and sauna culture." },
        { name: "Espoo", population: 0.30, area: "528 km\u00B2", founded: "1458", landmarks: ["Nuuksio National Park", "WeeGee Exhibition Centre", "Aalto University"], gdp: "\u20AC20B", avgSalary: "\u20AC3,300/mo", description: "Finland's second city and tech hub, home to Aalto University, Nokia headquarters, and stunning lakeside nature." },
        { name: "Tampere", population: 0.24, area: "525 km\u00B2", founded: "1779", landmarks: ["S\u00E4rk\u00E4nniemi", "Vapriikki Museum", "Pyynikki Tower", "Finlayson Area"], gdp: "\u20AC13B", avgSalary: "\u20AC2,800/mo", description: "Finland's 'Manchester' between two lakes, Tampere has reinvented its industrial heritage into vibrant cultural spaces and is famous for its sauna culture." },
        { name: "Vantaa", population: 0.24, area: "240 km\u00B2", founded: "1972", landmarks: ["Helsinki Airport", "Heureka Science Centre", "Tikkurila"], gdp: "\u20AC12B", avgSalary: "\u20AC3,000/mo", description: "Home to Helsinki Airport, Vantaa is a diverse, growing city with excellent science education facilities." },
        { name: "Oulu", population: 0.21, area: "3,817 km\u00B2", founded: "1605", landmarks: ["Nallikari Beach", "Tietomaa Science Centre", "Market Hall"], gdp: "\u20AC8B", avgSalary: "\u20AC2,700/mo", description: "The tech capital of Northern Finland, Oulu is known for air guitar championships, cycling culture, and proximity to the Arctic." }
    ],
    "France": [
        { name: "Paris", population: 2.16, area: "105 km\u00B2", founded: "3rd century BC", landmarks: ["Eiffel Tower", "Louvre Museum", "Notre-Dame", "Arc de Triomphe", "Sacr\u00E9-C\u0153ur"], gdp: "\u20AC710B", avgSalary: "\u20AC3,200/mo", description: "The City of Light is the world's most visited city, a global center for art, fashion, gastronomy, and culture with an unrivaled concentration of iconic monuments." },
        { name: "Marseille", population: 0.87, area: "241 km\u00B2", founded: "600 BC", landmarks: ["Notre-Dame de la Garde", "Vieux-Port", "MuCEM", "Calanques"], gdp: "\u20AC52B", avgSalary: "\u20AC2,300/mo", description: "France's oldest city and largest port, Marseille is a multicultural Mediterranean melting pot with stunning coastal landscapes." },
        { name: "Lyon", population: 0.52, area: "48 km\u00B2", founded: "43 BC", landmarks: ["Basilica of Fourvi\u00E8re", "Vieux Lyon", "Traboules", "Mus\u00E9e des Confluences"], gdp: "\u20AC78B", avgSalary: "\u20AC2,500/mo", description: "France's gastronomic capital with a UNESCO-listed Renaissance old town, Lyon is also a major biotech and pharmaceutical hub." },
        { name: "Toulouse", population: 0.49, area: "118 km\u00B2", founded: "8th century BC", landmarks: ["Capitole", "Cit\u00E9 de l'Espace", "Basilica of Saint-Sernin", "Canal du Midi"], gdp: "\u20AC42B", avgSalary: "\u20AC2,400/mo", description: "The 'Pink City' is Europe's aerospace capital (Airbus HQ), with France's largest university campus and vibrant occitan culture." },
        { name: "Nice", population: 0.34, area: "72 km\u00B2", founded: "350 BC", landmarks: ["Promenade des Anglais", "Vieux Nice", "Castle Hill", "Marc Chagall Museum"], gdp: "\u20AC28B", avgSalary: "\u20AC2,300/mo", description: "Queen of the French Riviera, Nice dazzles with its turquoise sea, Belle \u00C9poque architecture, and world-class art museums." }
    ],
    "Germany": [
        { name: "Berlin", population: 3.85, area: "892 km\u00B2", founded: "1237", landmarks: ["Brandenburg Gate", "Berlin Wall Memorial", "Reichstag", "Museum Island", "East Side Gallery"], gdp: "\u20AC175B", avgSalary: "\u20AC2,600/mo", description: "Germany's capital reinvented itself after reunification to become Europe's startup capital and a magnet for creatives worldwide." },
        { name: "Hamburg", population: 1.90, area: "755 km\u00B2", founded: "808", landmarks: ["Elbphilharmonie", "Speicherstadt", "Miniatur Wunderland", "Reeperbahn"], gdp: "\u20AC130B", avgSalary: "\u20AC2,800/mo", description: "Germany's gateway to the world, Hamburg is a maritime city with Europe's third-largest port, a stunning new concert hall, and legendary nightlife." },
        { name: "Munich", population: 1.47, area: "310 km\u00B2", founded: "1158", landmarks: ["Marienplatz", "Neuschwanstein Castle", "Englischer Garten", "BMW Museum", "Oktoberfest"], gdp: "\u20AC125B", avgSalary: "\u20AC3,100/mo", description: "Bavaria's capital combines traditional beer halls and lederhosen with cutting-edge tech companies and the Alps on the doorstep." },
        { name: "Cologne", population: 1.08, area: "405 km\u00B2", founded: "38 BC", landmarks: ["Cologne Cathedral", "Hohenzollern Bridge", "Museum Ludwig", "Chocolate Museum"], gdp: "\u20AC58B", avgSalary: "\u20AC2,500/mo", description: "Home to Germany's most visited landmark (the Gothic cathedral) and famous carnival, Cologne is a media capital on the Rhine." },
        { name: "Frankfurt", population: 0.76, area: "248 km\u00B2", founded: "794", landmarks: ["R\u00F6merberg", "European Central Bank", "Palmengarten", "Skyline"], gdp: "\u20AC95B", avgSalary: "\u20AC3,200/mo", description: "Germany's financial capital hosts the ECB and continental Europe's largest stock exchange, with a dramatic Manhattan-like skyline." }
    ],
    "Greece": [
        { name: "Athens", population: 0.66, area: "39 km\u00B2", founded: "3000 BC", landmarks: ["Acropolis", "Parthenon", "Plaka", "Ancient Agora", "National Archaeological Museum"], gdp: "\u20AC85B", avgSalary: "\u20AC1,100/mo", description: "The cradle of Western civilization, Athens blends 3,000 years of history with a vibrant modern food scene, street art, and nightlife." },
        { name: "Thessaloniki", population: 0.32, area: "19 km\u00B2", founded: "315 BC", landmarks: ["White Tower", "Rotunda", "Aristotle Square", "Ano Poli"], gdp: "\u20AC18B", avgSalary: "\u20AC900/mo", description: "Greece's cultural capital with Byzantine churches, a legendary food scene, and a lively waterfront that earned it the nickname 'the co-capital'." },
        { name: "Patras", population: 0.17, area: "126 km\u00B2", founded: "3rd millennium BC", landmarks: ["Rio-Antirrio Bridge", "Patras Castle", "Carnival"], gdp: "\u20AC5B", avgSalary: "\u20AC850/mo", description: "Greece's third city is famous for its spectacular carnival (one of Europe's largest), a gateway to the Peloponnese and western Greece." },
        { name: "Heraklion", population: 0.17, area: "245 km\u00B2", founded: "824 AD", landmarks: ["Knossos Palace", "Venetian Fortress", "Archaeological Museum"], gdp: "\u20AC4.5B", avgSalary: "\u20AC900/mo", description: "Gateway to the Minoan civilization on Crete, Heraklion combines ancient ruins with Venetian architecture and excellent Cretan cuisine." },
        { name: "Larissa", population: 0.14, area: "123 km\u00B2", founded: "2000 BC", landmarks: ["Ancient Theatre", "Alcazar Park", "Bezesteni Market"], gdp: "\u20AC3B", avgSalary: "\u20AC800/mo", description: "Central Greece's largest city, Larissa is an agricultural hub with ancient theatres and proximity to Mount Olympus." }
    ],
    "Hungary": [
        { name: "Budapest", population: 1.75, area: "525 km\u00B2", founded: "1873", landmarks: ["Parliament Building", "Buda Castle", "Fisherman's Bastion", "Sz\u00E9chenyi Thermal Bath", "Chain Bridge"], gdp: "\u20AC68B", avgSalary: "\u20AC1,200/mo", description: "The 'Pearl of the Danube' unites hilly Buda and flat Pest across Europe's most stunning river panorama, with thermal baths, ruin bars, and grand architecture." },
        { name: "Debrecen", population: 0.20, area: "462 km\u00B2", founded: "1235", landmarks: ["Great Reformed Church", "D\u00E9ri Museum", "Great Forest Park"], gdp: "\u20AC6B", avgSalary: "\u20AC900/mo", description: "Hungary's second city and historical capital during crises, Debrecen is a university town with excellent thermal baths and calvinist heritage." },
        { name: "Szeged", population: 0.16, area: "281 km\u00B2", founded: "1183", landmarks: ["Votive Church", "Tisza River", "Szeged Open-Air Festival"], gdp: "\u20AC4.5B", avgSalary: "\u20AC850/mo", description: "The 'City of Sunshine' rebuilt in Art Nouveau style after an 1879 flood, famous for its paprika, salami, and open-air theater." },
        { name: "Miskolc", population: 0.15, area: "237 km\u00B2", founded: "1364", landmarks: ["Cave Bath", "Diósgy\u0151r Castle", "Avas Hill"], gdp: "\u20AC3.5B", avgSalary: "\u20AC800/mo", description: "Northeast Hungary's largest city, unique for its cave thermal bath carved into limestone hills and medieval castle." },
        { name: "P\u00E9cs", population: 0.14, area: "163 km\u00B2", founded: "Roman era", landmarks: ["Early Christian Necropolis (UNESCO)", "Zsolnay Quarter", "Mosque of Pasha Qasim"], gdp: "\u20AC3B", avgSalary: "\u20AC800/mo", description: "A Mediterranean-feeling city with UNESCO early Christian tombs, Ottoman mosques, and the famous Zsolnay porcelain heritage." }
    ],
    "Ireland": [
        { name: "Dublin", population: 0.59, area: "115 km\u00B2", founded: "841", landmarks: ["Trinity College", "Temple Bar", "Guinness Storehouse", "Ha'penny Bridge", "St. Patrick's Cathedral"], gdp: "\u20AC120B", avgSalary: "\u20AC3,400/mo", description: "Ireland's capital is Europe's tech hub (Google, Meta, Apple HQs), combined with literary heritage, Georgian architecture, and legendary pub culture." },
        { name: "Cork", population: 0.21, area: "187 km\u00B2", founded: "6th century", landmarks: ["English Market", "Shandon Bells", "University College Cork", "Blarney Castle"], gdp: "\u20AC25B", avgSalary: "\u20AC2,800/mo", description: "Ireland's 'rebel city' and food capital, Cork is a charming riverside city with excellent restaurants and a thriving pharmaceutical sector." },
        { name: "Galway", population: 0.08, area: "50 km\u00B2", founded: "1124", landmarks: ["Spanish Arch", "Eyre Square", "Claddagh", "Galway Cathedral"], gdp: "\u20AC8B", avgSalary: "\u20AC2,600/mo", description: "Ireland's cultural heart on the Wild Atlantic Way, Galway is famous for its arts festivals, traditional music sessions, and bohemian spirit." },
        { name: "Limerick", population: 0.06, area: "20 km\u00B2", founded: "812", landmarks: ["King John's Castle", "Hunt Museum", "Treaty Stone"], gdp: "\u20AC7B", avgSalary: "\u20AC2,500/mo", description: "A medieval city on the Shannon, Limerick is reinventing itself with tech investment, street art, and its rugby heritage." },
        { name: "Waterford", population: 0.05, area: "42 km\u00B2", founded: "914", landmarks: ["Waterford Crystal", "Reginald's Tower", "Viking Triangle"], gdp: "\u20AC4B", avgSalary: "\u20AC2,300/mo", description: "Ireland's oldest city, founded by Vikings, famous worldwide for Waterford Crystal and its well-preserved medieval quarter." }
    ],
    "Italy": [
        { name: "Rome", population: 2.87, area: "1,285 km\u00B2", founded: "753 BC", landmarks: ["Colosseum", "Vatican City", "Trevi Fountain", "Pantheon", "Roman Forum"], gdp: "\u20AC150B", avgSalary: "\u20AC1,800/mo", description: "The Eternal City layers 2,800 years of history with world-class art, architecture, and cuisine. Every corner reveals ancient ruins, Renaissance masterpieces, or Baroque fountains." },
        { name: "Milan", population: 1.40, area: "182 km\u00B2", founded: "400 BC", landmarks: ["Duomo di Milano", "La Scala", "The Last Supper", "Galleria Vittorio Emanuele II"], gdp: "\u20AC200B", avgSalary: "\u20AC2,200/mo", description: "Italy's financial and fashion capital, Milan hosts Fashion Week, the world's most famous opera house, and Leonardo's Last Supper." },
        { name: "Naples", population: 0.91, area: "119 km\u00B2", founded: "470 BC", landmarks: ["Pompeii", "Mount Vesuvius", "Naples Underground", "Spaccanapoli"], gdp: "\u20AC45B", avgSalary: "\u20AC1,300/mo", description: "The chaotic, passionate birthplace of pizza, Naples sits beneath Vesuvius with an underground city and the nearby ruins of Pompeii." },
        { name: "Turin", population: 0.85, area: "130 km\u00B2", founded: "3rd century BC", landmarks: ["Mole Antonelliana", "Egyptian Museum", "Royal Palace", "Fiat Lingotto"], gdp: "\u20AC48B", avgSalary: "\u20AC1,900/mo", description: "Italy's first capital and home of Fiat, Turin is an elegant baroque city with the world's most important Egyptian museum outside Cairo." },
        { name: "Palermo", population: 0.67, area: "159 km\u00B2", founded: "734 BC", landmarks: ["Palazzo dei Normanni", "Cathedral", "Teatro Massimo", "Ballar\u00F2 Market"], gdp: "\u20AC20B", avgSalary: "\u20AC1,200/mo", description: "Sicily's vibrant capital blends Arab, Norman, and Baroque heritage with legendary street food markets and a raw, authentic energy." }
    ],
    "Netherlands": [
        { name: "Amsterdam", population: 0.92, area: "219 km\u00B2", founded: "1275", landmarks: ["Rijksmuseum", "Anne Frank House", "Van Gogh Museum", "Canal Ring (UNESCO)", "Dam Square"], gdp: "\u20AC105B", avgSalary: "\u20AC3,100/mo", description: "A city of canals, bicycles, and tolerance, Amsterdam packs world-class museums, creative industries, and a legendary nightlife into its compact center." },
        { name: "Rotterdam", population: 0.65, area: "325 km\u00B2", founded: "1270", landmarks: ["Erasmus Bridge", "Cube Houses", "Markthal", "Euromast"], gdp: "\u20AC50B", avgSalary: "\u20AC2,900/mo", description: "Europe's largest port city, Rotterdam was rebuilt after WWII with bold modern architecture and is now a world-class design and architecture destination." },
        { name: "The Hague", population: 0.55, area: "98 km\u00B2", founded: "1230", landmarks: ["Peace Palace (ICJ)", "Mauritshuis", "Binnenhof", "Scheveningen Beach"], gdp: "\u20AC35B", avgSalary: "\u20AC3,000/mo", description: "The seat of Dutch government and International Court of Justice, The Hague combines political prestige with a beautiful beach resort." },
        { name: "Utrecht", population: 0.36, area: "99 km\u00B2", founded: "47 AD", landmarks: ["Dom Tower", "Canals", "Rietveld Schr\u00F6der House (UNESCO)", "Railway Museum"], gdp: "\u20AC25B", avgSalary: "\u20AC2,800/mo", description: "A medieval gem with unique wharf-level canal terraces, Utrecht is the Netherlands' fastest-growing city and a cycling paradise." },
        { name: "Eindhoven", population: 0.24, area: "89 km\u00B2", founded: "1232", landmarks: ["Strijp-S", "Van Abbemuseum", "Philips Stadium", "Evoluon"], gdp: "\u20AC22B", avgSalary: "\u20AC2,900/mo", description: "The 'City of Light' and brainport of the Netherlands, Eindhoven is a design and technology hotspot that grew around Philips electronics." }
    ],
    "Norway": [
        { name: "Oslo", population: 0.70, area: "454 km\u00B2", founded: "1040", landmarks: ["Opera House", "Vigeland Park", "Munch Museum", "Holmenkollen", "Akershus Fortress"], gdp: "\u20AC75B", avgSalary: "\u20AC4,200/mo", description: "Norway's compact capital on the fjord, Oslo combines world-class museums, stunning architecture, and wilderness accessible by metro." },
        { name: "Bergen", population: 0.28, area: "465 km\u00B2", founded: "1070", landmarks: ["Bryggen (UNESCO)", "Fl\u00F8ibanen", "Fish Market", "Edvard Grieg Museum"], gdp: "\u20AC22B", avgSalary: "\u20AC3,800/mo", description: "Gateway to the fjords, Bergen's UNESCO-listed Hanseatic wharf and surrounding seven mountains make it one of Europe's most scenic cities." },
        { name: "Stavanger", population: 0.14, area: "71 km\u00B2", founded: "1125", landmarks: ["Pulpit Rock", "Norwegian Petroleum Museum", "Old Stavanger", "Swords in Rock"], gdp: "\u20AC25B", avgSalary: "\u20AC4,000/mo", description: "Norway's oil capital combines energy wealth with street art, a charming old wooden town, and proximity to the iconic Pulpit Rock." },
        { name: "Trondheim", population: 0.21, area: "342 km\u00B2", founded: "997", landmarks: ["Nidaros Cathedral", "Old Town Bridge", "Kristiansten Fortress", "Bakklandet"], gdp: "\u20AC15B", avgSalary: "\u20AC3,700/mo", description: "Norway's historical capital and home to Scandinavia's largest medieval cathedral, Trondheim is a tech and university city." },
        { name: "Troms\u00F8", population: 0.08, area: "2,558 km\u00B2", founded: "1794", landmarks: ["Arctic Cathedral", "Polaria", "Northern Lights Observatory", "Cable Car"], gdp: "\u20AC5B", avgSalary: "\u20AC3,600/mo", description: "The 'Gateway to the Arctic' is the world's northernmost city of its size, famous for Northern Lights, midnight sun, and Arctic expeditions." }
    ],
    "Poland": [
        { name: "Warsaw", population: 1.86, area: "517 km\u00B2", founded: "1300", landmarks: ["Old Town (UNESCO)", "Palace of Culture", "Royal Castle", "Copernicus Science Centre", "\u0141azienki Park"], gdp: "\u20AC110B", avgSalary: "\u20AC1,500/mo", description: "Rebuilt from ashes after WWII, Warsaw is now a booming economic powerhouse that blends its reconstructed old town with soaring modern skyscrapers." },
        { name: "Krak\u00F3w", population: 0.80, area: "327 km\u00B2", founded: "7th century", landmarks: ["Wawel Castle", "Main Market Square", "St. Mary's Basilica", "Kazimierz", "Wieliczka Salt Mine"], gdp: "\u20AC35B", avgSalary: "\u20AC1,300/mo", description: "Poland's cultural capital with Europe's largest medieval market square, a royal castle, and a thriving arts scene in the former Jewish quarter." },
        { name: "\u0141\u00F3d\u017A", population: 0.67, area: "293 km\u00B2", founded: "1423", landmarks: ["Manufaktura", "Piotrkowska Street", "Ksi\u0119\u017Cy M\u0142yn"], gdp: "\u20AC18B", avgSalary: "\u20AC1,100/mo", description: "Poland's 'promised land' of textile industry fame, \u0141\u00F3d\u017A has reinvented its massive factories into creative hubs, film schools, and loft spaces." },
        { name: "Wroc\u0142aw", population: 0.64, area: "293 km\u00B2", founded: "1000", landmarks: ["Market Square", "Centennial Hall (UNESCO)", "Cathedral Island", "Wroc\u0142aw Dwarfs"], gdp: "\u20AC22B", avgSalary: "\u20AC1,300/mo", description: "The 'Venice of Poland' spans 12 islands and 130 bridges, famous for hundreds of hidden bronze dwarfs and a stunning market square." },
        { name: "Pozna\u0144", population: 0.53, area: "262 km\u00B2", founded: "968", landmarks: ["Old Market Square", "Cathedral Island", "Imperial Castle", "Pozna\u0144 Goats"], gdp: "\u20AC20B", avgSalary: "\u20AC1,300/mo", description: "Where Poland began \u2014 Pozna\u0144 is a prosperous trade fair city with a colorful Renaissance square and famous mechanical goats." }
    ],
    "Portugal": [
        { name: "Lisbon", population: 0.55, area: "100 km\u00B2", founded: "1200 BC", landmarks: ["Bel\u00E9m Tower", "Jer\u00F3nimos Monastery", "Alfama", "Tram 28", "Time Out Market"], gdp: "\u20AC75B", avgSalary: "\u20AC1,300/mo", description: "Built on seven hills above the Tagus, Lisbon enchants with fado music, azulejo tiles, pastel-colored buildings, and Europe's sunniest capital vibes." },
        { name: "Porto", population: 0.24, area: "42 km\u00B2", founded: "275 BC", landmarks: ["Ribeira (UNESCO)", "Livraria Lello", "Cl\u00E9rigos Tower", "Port Wine Cellars", "S\u00E3o Bento Station"], gdp: "\u20AC28B", avgSalary: "\u20AC1,100/mo", description: "Portugal's second city gives its name to port wine and the country itself. Its UNESCO riverfront and azulejo-covered churches are unforgettable." },
        { name: "Vila Nova de Gaia", population: 0.30, area: "168 km\u00B2", founded: "Roman era", landmarks: ["Port Wine Cellars", "Monastery of Serra do Pilar", "Gaia Cable Car"], gdp: "\u20AC8B", avgSalary: "\u20AC1,000/mo", description: "Facing Porto across the Douro, Gaia is home to the famous port wine lodges and stunning river views." },
        { name: "Amadora", population: 0.18, area: "24 km\u00B2", founded: "1979", landmarks: ["Reboleira", "Amadora International Comics Festival"], gdp: "\u20AC5B", avgSalary: "\u20AC1,000/mo", description: "Part of Greater Lisbon, Amadora is Portugal's most densely populated city and hosts Europe's largest comic book festival." },
        { name: "Braga", population: 0.14, area: "184 km\u00B2", founded: "Roman era", landmarks: ["Bom Jesus do Monte", "Braga Cathedral", "Theatro Circo"], gdp: "\u20AC5B", avgSalary: "\u20AC950/mo", description: "Portugal's religious capital and one of the oldest Christian cities, with stunning baroque churches and a youthful university vibe." }
    ],
    "Romania": [
        { name: "Bucharest", population: 2.10, area: "228 km\u00B2", founded: "1459", landmarks: ["Palace of Parliament", "Old Town", "Romanian Athenaeum", "Village Museum", "Herestr\u0103u Park"], gdp: "\u20AC62B", avgSalary: "\u20AC1,200/mo", description: "Once called 'Little Paris,' Bucharest combines Belle \u00C9poque elegance with communist-era monumentalism and a booming tech startup scene." },
        { name: "Cluj-Napoca", population: 0.32, area: "179 km\u00B2", founded: "1213", landmarks: ["St. Michael's Church", "Botanical Garden", "Central Park", "Bánffy Palace"], gdp: "\u20AC12B", avgSalary: "\u20AC1,100/mo", description: "Romania's unofficial second capital and IT hub, Cluj is a vibrant university city with Transylvanian charm and Europe's largest electronic music festival (Untold)." },
        { name: "Timi\u0219oara", population: 0.32, area: "130 km\u00B2", founded: "1212", landmarks: ["Union Square", "Orthodox Cathedral", "Timi\u0219oara Revolution Museum"], gdp: "\u20AC8B", avgSalary: "\u20AC1,000/mo", description: "European Capital of Culture 2023, Timi\u0219oara was the first European city with electric street lighting and birthplace of the 1989 revolution." },
        { name: "Ia\u0219i", population: 0.29, area: "94 km\u00B2", founded: "1408", landmarks: ["Palace of Culture", "Copou Park", "Three Holy Hierarchs Monastery"], gdp: "\u20AC6B", avgSalary: "\u20AC950/mo", description: "Moldova's historical capital and Romania's cultural heart, Ia\u0219i is a university city where Romanian literature and modern identity were born." },
        { name: "Constan\u021Ba", population: 0.28, area: "125 km\u00B2", founded: "657 BC", landmarks: ["Casino", "Roman Mosaic", "Mamaia Beach", "Genoese Lighthouse"], gdp: "\u20AC6B", avgSalary: "\u20AC900/mo", description: "Romania's gateway to the Black Sea, founded by Greeks as Tomis, with ancient ruins, a grand (abandoned) Art Nouveau casino, and lively beach resorts." }
    ],
    "Spain": [
        { name: "Madrid", population: 3.40, area: "604 km\u00B2", founded: "9th century", landmarks: ["Royal Palace", "Prado Museum", "Retiro Park", "Puerta del Sol", "Plaza Mayor"], gdp: "\u20AC230B", avgSalary: "\u20AC2,200/mo", description: "Spain's capital sits at the geographic center of the Iberian Peninsula, pulsing with world-class art museums, late-night dining, and passionate football." },
        { name: "Barcelona", population: 1.66, area: "101 km\u00B2", founded: "230 BC", landmarks: ["Sagrada Fam\u00EDlia", "Park G\u00FCell", "La Rambla", "Casa Batll\u00F3", "Gothic Quarter"], gdp: "\u20AC180B", avgSalary: "\u20AC2,100/mo", description: "Gaud\u00ED's masterpiece city on the Mediterranean, Barcelona blends modernist architecture, beach culture, and Catalan identity into an irresistible package." },
        { name: "Valencia", population: 0.80, area: "135 km\u00B2", founded: "138 BC", landmarks: ["City of Arts and Sciences", "La Lonja (UNESCO)", "Central Market", "Turia Gardens"], gdp: "\u20AC55B", avgSalary: "\u20AC1,800/mo", description: "Birthplace of paella and home to Calatrava's futuristic City of Arts and Sciences, Valencia blends history, cuisine, and innovation." },
        { name: "Seville", population: 0.69, area: "140 km\u00B2", founded: "8th century BC", landmarks: ["Alc\u00E1zar", "Cathedral & Giralda", "Plaza de Espa\u00F1a", "Metropol Parasol"], gdp: "\u20AC32B", avgSalary: "\u20AC1,600/mo", description: "The soul of Andalusia, Seville intoxicates with flamenco, tapas, Moorish palaces, and orange-blossom-scented plazas." },
        { name: "Zaragoza", population: 0.67, area: "974 km\u00B2", founded: "24 BC", landmarks: ["Basilica del Pilar", "Aljafer\u00EDa Palace", "Expo 2008 site"], gdp: "\u20AC25B", avgSalary: "\u20AC1,700/mo", description: "Midway between Madrid and Barcelona, Zaragoza has Roman, Moorish, and Renaissance layers plus one of Spain's most revered basilicas." }
    ],
    "Sweden": [
        { name: "Stockholm", population: 0.98, area: "188 km\u00B2", founded: "1252", landmarks: ["Gamla Stan", "Vasa Museum", "City Hall", "ABBA Museum", "Djurg\u00E5rden"], gdp: "\u20AC110B", avgSalary: "\u20AC3,500/mo", description: "Spread across 14 islands, Stockholm is the 'Venice of the North' with a perfectly preserved medieval old town, innovative design, and tech startups." },
        { name: "Gothenburg", population: 0.58, area: "447 km\u00B2", founded: "1621", landmarks: ["Liseberg", "Universeum", "Haga District", "Archipelago"], gdp: "\u20AC38B", avgSalary: "\u20AC3,200/mo", description: "Sweden's friendly west-coast city is a foodie destination with Michelin stars, Volvo heritage, and a stunning archipelago." },
        { name: "Malm\u00F6", population: 0.35, area: "158 km\u00B2", founded: "1275", landmarks: ["Turning Torso", "\u00D6resund Bridge", "Malm\u00F6hus Castle", "Western Harbour"], gdp: "\u20AC18B", avgSalary: "\u20AC3,000/mo", description: "Sweden's most multicultural city, connected to Copenhagen by the \u00D6resund Bridge, with striking modern architecture and sustainable urban design." },
        { name: "Uppsala", population: 0.23, area: "2,189 km\u00B2", founded: "1286", landmarks: ["Uppsala Cathedral", "Uppsala University", "Gamla Uppsala", "Linnaeus Garden"], gdp: "\u20AC12B", avgSalary: "\u20AC3,100/mo", description: "Home to Scandinavia's oldest university (1477), Uppsala blends academic prestige with Viking burial mounds and Sweden's largest cathedral." },
        { name: "V\u00E4ster\u00E5s", population: 0.15, area: "963 km\u00B2", founded: "990", landmarks: ["Anundsh\u00F6g", "V\u00E4ster\u00E5s Cathedral", "Kokpunkten Observation Tower"], gdp: "\u20AC8B", avgSalary: "\u20AC2,900/mo", description: "A lakeside tech city that has grown from Viking origins to become a robotics and automation hub with Sweden's largest inland port." }
    ],
    "Switzerland": [
        { name: "Z\u00FCrich", population: 0.43, area: "88 km\u00B2", founded: "15 BC", landmarks: ["Bahnhofstrasse", "Lake Z\u00FCrich", "Grossm\u00FCnster", "Swiss National Museum", "Old Town"], gdp: "\u20AC95B", avgSalary: "\u20AC5,500/mo", description: "Switzerland's financial capital and most populous city, Z\u00FCrich combines banking prestige with a thriving arts scene, pristine lake, and Alpine views." },
        { name: "Geneva", population: 0.20, area: "16 km\u00B2", founded: "500 BC", landmarks: ["Jet d'Eau", "United Nations", "CERN", "Old Town", "Lake Geneva"], gdp: "\u20AC50B", avgSalary: "\u20AC5,200/mo", description: "The 'Peace Capital' hosts the UN, Red Cross, and CERN. A cosmopolitan French-speaking city with Mont Blanc views and watchmaking heritage." },
        { name: "Basel", population: 0.18, area: "24 km\u00B2", founded: "44 BC", landmarks: ["Art Basel", "Rhine Swimming", "Foundation Beyeler", "Vitra Design Museum"], gdp: "\u20AC35B", avgSalary: "\u20AC5,000/mo", description: "Where three countries meet, Basel is a pharma powerhouse (Novartis, Roche) and cultural gem with more museums per capita than any Swiss city." },
        { name: "Bern", population: 0.13, area: "51 km\u00B2", founded: "1191", landmarks: ["Zytglogge Clock", "Federal Palace", "Bear Park", "Einstein House", "Old Town (UNESCO)"], gdp: "\u20AC22B", avgSalary: "\u20AC4,800/mo", description: "Switzerland's understated capital has a UNESCO medieval old town, Einstein's former apartment, and the bears that gave the city its name." },
        { name: "Lausanne", population: 0.14, area: "41 km\u00B2", founded: "Roman era", landmarks: ["Olympic Museum", "Cathedral", "EPFL", "Lavaux Vineyards (UNESCO)"], gdp: "\u20AC18B", avgSalary: "\u20AC4,800/mo", description: "The Olympic Capital on Lake Geneva, Lausanne combines a world-class technical university (EPFL) with hillside vineyards and sporting prestige." }
    ],
    "United Kingdom": [
        { name: "London", population: 9.00, area: "1,572 km\u00B2", founded: "47 AD", landmarks: ["Big Ben", "Tower of London", "Buckingham Palace", "British Museum", "Tower Bridge"], gdp: "\u20AC580B", avgSalary: "\u20AC3,100/mo", description: "A global city and leading financial center, London seamlessly blends nearly 2,000 years of history with cutting-edge modernity across its diverse boroughs." },
        { name: "Birmingham", population: 1.14, area: "268 km\u00B2", founded: "7th century", landmarks: ["Bullring", "Library of Birmingham", "Cadbury World", "Jewellery Quarter"], gdp: "\u20AC70B", avgSalary: "\u20AC2,200/mo", description: "England's second city and birthplace of the Industrial Revolution, Birmingham has more canals than Venice and a thriving food and music scene." },
        { name: "Manchester", population: 0.55, area: "116 km\u00B2", founded: "79 AD", landmarks: ["Old Trafford", "Northern Quarter", "John Rylands Library", "MediaCityUK"], gdp: "\u20AC72B", avgSalary: "\u20AC2,300/mo", description: "The original industrial city reinvented as a creative and tech hub, Manchester is world-famous for football, music (Oasis, Joy Division), and nightlife." },
        { name: "Glasgow", population: 0.63, area: "175 km\u00B2", founded: "6th century", landmarks: ["Kelvingrove Museum", "Glasgow Cathedral", "Riverside Museum", "Buchanan Street"], gdp: "\u20AC45B", avgSalary: "\u20AC2,100/mo", description: "Scotland's largest city is a cultural powerhouse with outstanding museums (mostly free), Art Nouveau heritage, and famously friendly locals." },
        { name: "Edinburgh", population: 0.53, area: "264 km\u00B2", founded: "7th century", landmarks: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat", "Scott Monument", "Fringe Festival"], gdp: "\u20AC40B", avgSalary: "\u20AC2,400/mo", description: "Scotland's capital is a dramatic city of volcanic hills and medieval closes, hosting the world's largest arts festival every August." }
    ],
    "Ukraine": [
        { name: "Kyiv", population: 2.95, area: "839 km\u00B2", founded: "482", landmarks: ["Saint Sophia Cathedral (UNESCO)", "Kyiv Pechersk Lavra", "Maidan Nezalezhnosti", "Golden Gate"], gdp: "\u20AC35B", avgSalary: "\u20AC700/mo", description: "One of Eastern Europe's oldest cities, Kyiv's golden-domed monasteries and broad boulevards reflect its role as the birthplace of Slavic civilization." },
        { name: "Kharkiv", population: 1.43, area: "350 km\u00B2", founded: "1654", landmarks: ["Freedom Square", "Derzhprom", "Shevchenko Park", "Mirror Stream"], gdp: "\u20AC12B", avgSalary: "\u20AC550/mo", description: "Ukraine's second city and former capital, Kharkiv is a major university and tech hub with constructivist architecture and one of Europe's largest squares." },
        { name: "Odesa", population: 1.02, area: "237 km\u00B2", founded: "1794", landmarks: ["Potemkin Stairs", "Opera House", "Deribasivska Street", "Catacombs"], gdp: "\u20AC8B", avgSalary: "\u20AC500/mo", description: "The 'Pearl of the Black Sea' is Ukraine's humor capital, a cosmopolitan port city with stunning neoclassical architecture and vibrant beach culture." },
        { name: "Dnipro", population: 0.98, area: "405 km\u00B2", founded: "1776", landmarks: ["Monastyrskyi Island", "Dnipro Embankment", "Menorah Center"], gdp: "\u20AC9B", avgSalary: "\u20AC550/mo", description: "Ukraine's space and rocket industry hub on the Dnieper River, Dnipro is a major industrial and tech city with a growing startup scene." },
        { name: "Lviv", population: 0.72, area: "149 km\u00B2", founded: "1256", landmarks: ["Rynok Square (UNESCO)", "Lviv Opera House", "High Castle", "Armenian Cathedral"], gdp: "\u20AC5B", avgSalary: "\u20AC500/mo", description: "Western Ukraine's cultural jewel, Lviv's UNESCO old town blends Polish, Austrian, and Ukrainian heritage with legendary coffee culture." }
    ]
};
