const europeanCountries = [
    { name: "Albania", capital: "Tirana", flag: "\u{1F1E6}\u{1F1F1}", population: 2.8 },
    { name: "Andorra", capital: "Andorra la Vella", flag: "\u{1F1E6}\u{1F1E9}", population: 0.08 },
    { name: "Austria", capital: "Vienna", flag: "\u{1F1E6}\u{1F1F9}", population: 9.1 },
    { name: "Belarus", capital: "Minsk", flag: "\u{1F1E7}\u{1F1FE}", population: 9.4 },
    { name: "Belgium", capital: "Brussels", flag: "\u{1F1E7}\u{1F1EA}", population: 11.6 },
    { name: "Bosnia and Herzegovina", capital: "Sarajevo", flag: "\u{1F1E7}\u{1F1E6}", population: 3.3 },
    { name: "Bulgaria", capital: "Sofia", flag: "\u{1F1E7}\u{1F1EC}", population: 6.9 },
    { name: "Croatia", capital: "Zagreb", flag: "\u{1F1ED}\u{1F1F7}", population: 3.9 },
    { name: "Cyprus", capital: "Nicosia", flag: "\u{1F1E8}\u{1F1FE}", population: 1.2 },
    { name: "Czech Republic", capital: "Prague", flag: "\u{1F1E8}\u{1F1FF}", population: 10.7 },
    { name: "Denmark", capital: "Copenhagen", flag: "\u{1F1E9}\u{1F1F0}", population: 5.9 },
    { name: "Estonia", capital: "Tallinn", flag: "\u{1F1EA}\u{1F1EA}", population: 1.3 },
    { name: "Finland", capital: "Helsinki", flag: "\u{1F1EB}\u{1F1EE}", population: 5.5 },
    { name: "France", capital: "Paris", flag: "\u{1F1EB}\u{1F1F7}", population: 67.8 },
    { name: "Germany", capital: "Berlin", flag: "\u{1F1E9}\u{1F1EA}", population: 83.2 },
    { name: "Greece", capital: "Athens", flag: "\u{1F1EC}\u{1F1F7}", population: 10.4 },
    { name: "Hungary", capital: "Budapest", flag: "\u{1F1ED}\u{1F1FA}", population: 9.7 },
    { name: "Iceland", capital: "Reykjavik", flag: "\u{1F1EE}\u{1F1F8}", population: 0.38 },
    { name: "Ireland", capital: "Dublin", flag: "\u{1F1EE}\u{1F1EA}", population: 5.1 },
    { name: "Italy", capital: "Rome", flag: "\u{1F1EE}\u{1F1F9}", population: 59.0 },
    { name: "Kosovo", capital: "Pristina", flag: "\u{1F1FD}\u{1F1F0}", population: 1.8 },
    { name: "Latvia", capital: "Riga", flag: "\u{1F1F1}\u{1F1FB}", population: 1.8 },
    { name: "Liechtenstein", capital: "Vaduz", flag: "\u{1F1F1}\u{1F1EE}", population: 0.04 },
    { name: "Lithuania", capital: "Vilnius", flag: "\u{1F1F1}\u{1F1F9}", population: 2.8 },
    { name: "Luxembourg", capital: "Luxembourg City", flag: "\u{1F1F1}\u{1F1FA}", population: 0.65 },
    { name: "Malta", capital: "Valletta", flag: "\u{1F1F2}\u{1F1F9}", population: 0.53 },
    { name: "Moldova", capital: "Chisinau", flag: "\u{1F1F2}\u{1F1E9}", population: 2.6 },
    { name: "Monaco", capital: "Monaco", flag: "\u{1F1F2}\u{1F1E8}", population: 0.04 },
    { name: "Montenegro", capital: "Podgorica", flag: "\u{1F1F2}\u{1F1EA}", population: 0.62 },
    { name: "Netherlands", capital: "Amsterdam", flag: "\u{1F1F3}\u{1F1F1}", population: 17.6 },
    { name: "North Macedonia", capital: "Skopje", flag: "\u{1F1F2}\u{1F1F0}", population: 2.1 },
    { name: "Norway", capital: "Oslo", flag: "\u{1F1F3}\u{1F1F4}", population: 5.5 },
    { name: "Poland", capital: "Warsaw", flag: "\u{1F1F5}\u{1F1F1}", population: 37.7 },
    { name: "Portugal", capital: "Lisbon", flag: "\u{1F1F5}\u{1F1F9}", population: 10.3 },
    { name: "Romania", capital: "Bucharest", flag: "\u{1F1F7}\u{1F1F4}", population: 19.0 },
    { name: "Russia", capital: "Moscow", flag: "\u{1F1F7}\u{1F1FA}", population: 144.1 },
    { name: "San Marino", capital: "San Marino", flag: "\u{1F1F8}\u{1F1F2}", population: 0.03 },
    { name: "Serbia", capital: "Belgrade", flag: "\u{1F1F7}\u{1F1F8}", population: 6.8 },
    { name: "Slovakia", capital: "Bratislava", flag: "\u{1F1F8}\u{1F1F0}", population: 5.5 },
    { name: "Slovenia", capital: "Ljubljana", flag: "\u{1F1F8}\u{1F1EE}", population: 2.1 },
    { name: "Spain", capital: "Madrid", flag: "\u{1F1EA}\u{1F1F8}", population: 47.4 },
    { name: "Sweden", capital: "Stockholm", flag: "\u{1F1F8}\u{1F1EA}", population: 10.5 },
    { name: "Switzerland", capital: "Bern", flag: "\u{1F1E8}\u{1F1ED}", population: 8.8 },
    { name: "Ukraine", capital: "Kyiv", flag: "\u{1F1FA}\u{1F1E6}", population: 37.0 },
    { name: "United Kingdom", capital: "London", flag: "\u{1F1EC}\u{1F1E7}", population: 67.7 },
    { name: "Vatican City", capital: "Vatican City", flag: "\u{1F1FB}\u{1F1E6}", population: 0.0008 }
];

const biggestCities = [
    { name: "Istanbul", country: "Turkey/Europe", population: 15.66 },
    { name: "Moscow", country: "Russia", population: 13.01 },
    { name: "London", country: "United Kingdom", population: 9.00 },
    { name: "Saint Petersburg", country: "Russia", population: 5.60 },
    { name: "Berlin", country: "Germany", population: 3.85 },
    { name: "Madrid", country: "Spain", population: 3.40 },
    { name: "Kyiv", country: "Ukraine", population: 2.95 },
    { name: "Rome", country: "Italy", population: 2.87 },
    { name: "Paris", country: "France", population: 2.16 },
    { name: "Bucharest", country: "Romania", population: 2.10 },
    { name: "Vienna", country: "Austria", population: 2.00 },
    { name: "Hamburg", country: "Germany", population: 1.90 },
    { name: "Warsaw", country: "Poland", population: 1.86 },
    { name: "Budapest", country: "Hungary", population: 1.75 },
    { name: "Barcelona", country: "Spain", population: 1.66 }
];

const topFiveCities = [
    {
        rank: 1,
        name: "Istanbul",
        country: "Turkey (European side)",
        population: "15.66 million",
        area: "5,461 km\u00B2",
        founded: "660 BC",
        gdp: "\u20AC245 billion",
        description: "Straddling two continents, Istanbul is the cultural and economic heart of Turkey. Once Constantinople, capital of the Byzantine and Ottoman empires, it boasts an unmatched historical legacy. The city serves as a bridge between East and West with a vibrant economy driven by finance, commerce, and tourism.",
        landmarks: ["Hagia Sophia", "Blue Mosque", "Topkapi Palace", "Grand Bazaar", "Bosphorus Bridge"],
        stats: { tourists: 20.2, costIndex: 34, avgSalary: "\u20AC850/mo", metro: "Yes (8 lines)" },
        tags: ["Transcontinental", "UNESCO Heritage", "Megacity", "Historical Capital"]
    },
    {
        rank: 2,
        name: "Moscow",
        country: "Russia",
        population: "13.01 million",
        area: "2,562 km\u00B2",
        founded: "1147",
        gdp: "\u20AC320 billion",
        description: "Russia's capital and largest city, Moscow is the political, economic, scientific, and cultural center of the country. Home to the Kremlin and Red Square, it has one of the world's most efficient metro systems and a thriving arts scene from the Bolshoi Theatre to Tretyakov Gallery.",
        landmarks: ["The Kremlin", "Red Square", "St. Basil's Cathedral", "Bolshoi Theatre", "Moscow Metro"],
        stats: { tourists: 17.5, costIndex: 41, avgSalary: "\u20AC1,200/mo", metro: "Yes (16 lines)" },
        tags: ["National Capital", "Financial Hub", "Cultural Center", "Historic"]
    },
    {
        rank: 3,
        name: "London",
        country: "United Kingdom",
        population: "9.00 million",
        area: "1,572 km\u00B2",
        founded: "47 AD",
        gdp: "\u20AC580 billion",
        description: "London is a global city and leading financial center. With its diverse population speaking over 300 languages, it's one of the most multicultural cities on Earth. From the historic Tower of London to cutting-edge architecture in the City, London seamlessly blends old and new.",
        landmarks: ["Big Ben", "Tower of London", "Buckingham Palace", "The British Museum", "Tower Bridge"],
        stats: { tourists: 30.1, costIndex: 75, avgSalary: "\u20AC3,100/mo", metro: "Yes (11 lines)" },
        tags: ["Global Finance", "Multicultural", "Royal Heritage", "Tech Hub"]
    },
    {
        rank: 4,
        name: "Saint Petersburg",
        country: "Russia",
        population: "5.60 million",
        area: "1,439 km\u00B2",
        founded: "1703",
        gdp: "\u20AC95 billion",
        description: "Founded by Peter the Great as Russia's 'Window to Europe,' Saint Petersburg is renowned for its baroque and neoclassical architecture, canals, and world-class museums. The Hermitage Museum alone houses over 3 million items, making it one of the world's largest and most prestigious art collections.",
        landmarks: ["Hermitage Museum", "Winter Palace", "Church of the Savior on Spilled Blood", "Peterhof Palace", "Nevsky Prospect"],
        stats: { tourists: 9.4, costIndex: 35, avgSalary: "\u20AC900/mo", metro: "Yes (5 lines)" },
        tags: ["Venice of North", "Cultural Capital", "UNESCO Heritage", "Imperial History"]
    },
    {
        rank: 5,
        name: "Berlin",
        country: "Germany",
        population: "3.85 million",
        area: "892 km\u00B2",
        founded: "1237",
        gdp: "\u20AC175 billion",
        description: "Germany's capital reinvented itself after reunification in 1990 to become Europe's startup capital and a magnet for creatives worldwide. Known for its vibrant nightlife, street art, and history museums, Berlin offers a unique blend of raw urban energy and deep historical significance.",
        landmarks: ["Brandenburg Gate", "Berlin Wall Memorial", "Reichstag Building", "Museum Island", "East Side Gallery"],
        stats: { tourists: 14.1, costIndex: 58, avgSalary: "\u20AC2,600/mo", metro: "Yes (10 lines)" },
        tags: ["Startup Capital", "Reunified City", "Creative Hub", "Historical"]
    }
];
